[package]
version = "0.1.0"
rust-version = "1.81.0"
edition = "2021"

name = "arcaea"
authors = ["Charlie"]
description = "A Rust Console Ascii Editor App <3"

[dependencies]
crossterm = "0.28.1"
unicode-width = "0.2.0"

[dev-dependencies]
tempfile = "3.19.1"
